config/routes.rb
Rails.application.routes.draw do
  root "creatures#index"
  
    resources :creatures

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
    def index 
        @creatures = Creature.all
    end

    def show
        @creature = Creature.find params[:id]
    end

    def new
        @creature = Creature.new
    end

    def edit
        @creature = Creature.find params[:id]
    end

    def create
        @creature = Creature.new(creature_params)

        if @creature.save
            redirect_to creature_path(@creature)
        end
    end

    def update
        @creature = Creature.find params[:id]
        if @creature.update(creature_params)
            redirect_to creature_path(@creature)
            
        else
            render :edit
        end
    end

    def destroy 
        @creature = Creature.find params[:id]
        @creature.destroy
        redirect_to creatures_path
    end 

    private 
    def creature_params
        creature_params = params.require(:creature).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<h1>Edit <%= @creature.name%> </h1>

<%= render "partials/creature_form", creature: @creature %>
<br />
<%= link_to creatures_path do%>
<div><button>Edit <%= @creature.name %></button></div>
<%end%>
<br />
<%=link_to creature_path(@creature.id), method: :delete, data: {confirm: "Are you sure?"}  do%> 
<div><button>Delete <%= @creature.name %></button></div>
<%end%>

app/views/creatures/index.html.erb
<h1>Bog Critters</h1>
<%= link_to "New Critter", new_creature_path%>

<% @creatures.each do |creature| %>
  <p>
    <label>Name:</label> <%= link_to "#{creature.name}", creature_path(creature.id) %><br>
    <label>Description:</label> <%= creature.description %>
  </p>
<% end %>

app/views/creatures/new.html.erb
<h1>New Critter</h1>

<%= render "partials/creature_form", creature: @creature %>
<br />
<%= link_to "Back to Them Critters", creatures_path%>

app/views/creatures/show.html.erb
<h1><%= @creature.name%></h1>
<h3>"<%= @creature.description%>"</h3>
<%= link_to "Edit #{@creature.name}", edit_creature_path%> <br />
<%= link_to "Back to Them Critters", creatures_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogAppOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/partials/_creature_form.html.erb
<%= form_for creature do |f|%>
    <%= f.label :name %>:<br />
    <%= f.text_field :name %><br />

    <%= f.label :description %>:<br />
    <%= f.text_area :description %><br />

    <%= f.submit %>
<% end %>